# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nathan Lanza
email: nathan@lanza.io
description: Someday, I'll start writing things here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lanza.io" # the base hostname & protocol for your site
twitter_username: lanzanathan
github_username:  nathanlanza

# Build settings
markdown: kramdown
